name: CI

on:
  push:

jobs:
  static_tests:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo Check
        uses: actions-rs/cargo@v1
        with:
          command: check

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Helipad
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
